### ISSUE TITLE
Ability to read files with non-standard extensions.

### ISSUE THREAD

**Issue by bhaskarvk** [ropensci/geojsonio#93]
Some geojson data on the web has the regular '.json' extension , these can't currently be read from geojson_read as they don't have a .geojson' extension.
Similarly for URLs there are at times request parameters, so the URL doesn't always end in the expected file extension. e.g. 

http://add.antarctica.ac.uk/repository/entry/get/Seamask_medium_res_polygon.kml?entryid=synth%3Af477219b-9121-44d6-afa6-d8552762dc45%3AL2JhY2tkcm9wcy9rbWwvU2VhbWFza19tZWRpdW1fcmVzX3BvbHlnb24ua21s

A simple fix would be to be able to specify the file type explicitly and using that instead of deriving it from the file extension.

**Comment by sckott** [comment]
right, `.json` extensions should work, and working on fixing urls that don't have extension on end

**Comment by bhaskarvk** [comment]
FWIW it was giving me errors reading geojsons with .json extensions which went away after renaming the file to .geojson.

**Comment by sckott** [comment]
That link above is dead now. Do you have other egs like that?

**Comment by sckott** [comment]
made some changes. reinstall from github, and try again. `.json` should work now, and URLs where extension is not at end should work now (though if there's no extension at all in the URL, we may not be able to handle it since we'd have to then guess what kind of file it is)

**Comment by bhaskarvk** [comment]
Still not working w/ latest commit.

```r
# Just to double check if I've the latest commit in my install.
> devtools::install_github('ropensci/geojsonio')
Skipping install of 'geojsonio' from a github remote, the SHA1 (8f2b4bf3) has not changed since last install.
  Use `force = TRUE` to force installation
> fName <- '~/code/exteral/github/gis-data/world.geo.json/countries.geo.json'
> spdf <- geojsonio::geojson_read(fName, method='local', what='sp')
Error in match.arg(fileext, c("shp", "kml", "geojson")) : 
  'arg' should be one of “shp”, “kml”, “geojson”
> 
```

The file came from https://github.com/johan/world.geo.json/

**Comment by sckott** [comment]
sorry, didn't fix the route where `what = 'sp'`, should work now. Will make this more general with `mime` pkg probably in addition to guessing file type from ext.

**Comment by sckott** [comment]
assuming this is sorted
